---
- name: Install nginx
  apt: name={{item}} state=present
  with_items:
  - nginx
- name: Copy nginx site config
  template: src=development dest=/etc/nginx/sites-available/default
- name: Enable nginx site
  file: src=/etc/nginx/sites-available/default
        dest=/etc/nginx/sites-enabled/default
        state=link
        force=yes
#- name: restart nginx
#  command: systemctl restart nginx
